"""empty message

Revision ID: a43c30eb7642
Revises: 32734587f923
Create Date: 2019-10-23 12:53:06.725409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a43c30eb7642'
down_revision = '32734587f923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_ibfk_1', 'otp', type_='foreignkey')
    op.drop_column('otp', 'userid')
    op.add_column('user', sa.Column('otp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'otp', ['otp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'otp_id')
    op.add_column('otp', sa.Column('userid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('otp_ibfk_1', 'otp', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###
