"""empty message

Revision ID: c29f42bd6221
Revises: a43c30eb7642
Create Date: 2019-10-23 15:17:12.175011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29f42bd6221'
down_revision = 'a43c30eb7642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_method', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Enum('N', 'Y'), server_default='Y', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_otp'), 'otp', ['otp'], unique=True)
    op.create_table('workfunctioncontext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Enum('N', 'Y'), server_default='Y', nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('orgunit_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['orgunit_id'], ['orgunit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workfunctioncontext_name'), 'workfunctioncontext', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('otp_mode', sa.String(length=20), nullable=True),
    sa.Column('allowemaillogin', sa.Enum('N', 'Y'), server_default='N', nullable=False),
    sa.Column('is_active', sa.Enum('N', 'Y'), server_default='Y', nullable=False),
    sa.Column('wfc_id', sa.Integer(), nullable=False),
    sa.Column('otp_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['otp_id'], ['otp.id'], ),
    sa.ForeignKeyConstraint(['wfc_id'], ['workfunctioncontext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('roles_n_user_map',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_n_user_map')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_workfunctioncontext_name'), table_name='workfunctioncontext')
    op.drop_table('workfunctioncontext')
    op.drop_index(op.f('ix_otp_otp'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
