"""changing many to one as pwdhistory to user instead of the otherway rond

Revision ID: 87dea70a4ccd
Revises: ee182cb03000
Create Date: 2019-10-31 10:28:49.271595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87dea70a4ccd'
down_revision = 'ee182cb03000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pwdhistory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pwdhistory', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_ibfk_3', 'user', type_='foreignkey')
    op.drop_column('user', 'pwd_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_3', 'user', 'pwdhistory', ['pwd_id'], ['id'])
    op.drop_constraint(None, 'pwdhistory', type_='foreignkey')
    op.drop_column('pwdhistory', 'user_id')
    # ### end Alembic commands ###
