"""adding force_pwd_change in User

Revision ID: aa6467516d25
Revises: 87dea70a4ccd
Create Date: 2019-11-06 14:11:13.160327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6467516d25'
down_revision = '87dea70a4ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('force_pwd_change', sa.Enum('N', 'Y'), server_default='N', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'force_pwd_change')
    # ### end Alembic commands ###
