"""pwdhistory report

Revision ID: ee182cb03000
Revises: 7c15bd01e59e
Create Date: 2019-10-31 09:35:40.998447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee182cb03000'
down_revision = '7c15bd01e59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwdhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('pwd_creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('last_logged_in', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('num_of_failed_attempt', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('pwd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'pwdhistory', ['pwd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'pwd_id')
    op.drop_column('user', 'num_of_failed_attempt')
    op.drop_column('user', 'last_logged_in')
    op.drop_table('pwdhistory')
    # ### end Alembic commands ###
