"""adding catalogue class

Revision ID: aa2c1c57d549
Revises: 33f94922a2fc
Create Date: 2019-02-10 11:10:19.630042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2c1c57d549'
down_revision = '33f94922a2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('endpoint_url_internal', sa.String(length=256), nullable=True),
    sa.Column('endpoint_url_external', sa.String(length=256), nullable=True),
    sa.Column('endpoint_url_admin', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_catalog_endpoint_url_admin'), ['endpoint_url_admin'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_catalog_endpoint_url_external'), ['endpoint_url_external'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_catalog_endpoint_url_internal'), ['endpoint_url_internal'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_catalog_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_catalog_name'))
        batch_op.drop_index(batch_op.f('ix_service_catalog_endpoint_url_internal'))
        batch_op.drop_index(batch_op.f('ix_service_catalog_endpoint_url_external'))
        batch_op.drop_index(batch_op.f('ix_service_catalog_endpoint_url_admin'))

    op.drop_table('service_catalog')
    # ### end Alembic commands ###
