user_auth_info_from: file # OSENV or file , leave it as file
user_auth_info_file_location: /home/bhujay/tlclient/user_settings.ini # change this location to users home dir 
fernet_key_file: /home/bhujay/tlclient/prod_farnetkeys
ssl_verify: False # leave it as is 

tl_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrFJNWRYL1o1AZnRfomUV0Wj5uGqd5AAcauK04xUnNjB4vI7tsUML6ouRXrAZ7LiF/EzhkKzHcDwK9fftBkjVMfmP+BOUOc2fRIXqeOKp3f5tEIm/QIYc9pfimuwpnps7xGJomVN6/9TGbahBLnKWbYolmnRnA9c+tfSSKXebJ+hCmCvbsPx9OAjx9b44H19v2gMrtSDJrad9KV5iXpsdH3lAwOzWxXVG7kou3c5Aje8UhaAApEKNV1vefQg+R3fAGDSoeY0rIhgMs0fDyJnObiKeo7qXV022dHVsTh272hDJe+NhIO1hNMsr3rPc9fLjoZGkKnIu48bHXHZ5K2FRR bhujay@ubuntu
